// <auto-generated />
using System;
using A2GestampApp.Infrastructure.Features.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A2GestampApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("A2GestampApp.Domain.Features.Inspection.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CycleTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalJudgement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperatorRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalJudgement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThirdImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("inspection", (string)null);
                });

            modelBuilder.Entity("A2GestampApp.Domain.Features.ProductionShift.Entities.ProductionShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("LastCycleTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastInspectionResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Produced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("production_shift", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
